### PR TITLE
Check if ITK-SNAP exists, exits program if not in manual_correction.py

### LINKED ISSUE #38: Check if command "ITK-SNAP" for windows exists in manual_correction.py
## Description
In the script `manual_correction.py`, to call ITK-SNAP, the command line is different for macOS and on windows. Right now, the script checks only if `itksnap` command exists and runs the command for windows `ITK-SNAP` if not. 

The purpose of this issue is to:
- Check if the command `ITK-SNAP` exists before running it.
- Raise an exception if none of the commands work. (Say to user to check if itk-snap is installed and if it was added to `PATH` variable)

### PR DESCRIPTION
**Pull request by sandrinebedard**
## Description
This PR addresses issue #38 for usage of ITK-SNAP for manual segmentations.
It includes:
- Check if windows command for itksnap `ITK-SNAP` exists.
- Raise an error and exit program if command for macOS /linux and for windows don't exist.

## Linked issues
Closes #38

### CODE REVIEW

**Comment by jcohenadad** [comment]
@alexfoias can you pls test it? (i have no time)-- thx

**Comment by alexfoias** [comment]
Sure. I'll test it.

**Comment by alexfoias** [comment]
When running **manual_correction.py** I get an error. I followed the installation procedure for the package listed here: https://github.com/sct-pipeline/ukbiobank-spinalcord-csa#installation

```
[23/02/21 3:21:44] (base) alex@NeuroPoly-MacBook-Pro cli % pwd
/Users/alex/code/ukbiobank-spinalcord-csa/pipeline_ukbiobank/cli
[23/02/21 3:21:45] (base) alex@NeuroPoly-MacBook-Pro cli % python manual_correction.py
Traceback (most recent call last):
  File "manual_correction.py", line 240, in <module>
    main()
  File "manual_correction.py", line 152, in main
    parser = get_parser()
  File "manual_correction.py", line 35, in get_parser
    formatter_class=utils.SmartFormatter,
AttributeError: module 'utils' has no attribute 'SmartFormatter'
```

**Comment by sandrinebedard** [comment]
> Did I do something wrong ?

@alexfoias let me check! I'll get back to you!

**Comment by sandrinebedard** [comment]
@alexfoias So this is weird, could you check that the class `SmartFormatter` is actually in [utils.py]( https://github.com/sct-pipeline/ukbiobank-spinalcord-csa/blob/master/utils.py) to start with?

**Comment by alexfoias** [comment]
yes it is.

**Comment by sandrinebedard** [comment]
@alexfoias the import of utils works `import utils`?

**Comment by sandrinebedard** [comment]
@alexfoias, I changed the import for `utils.py` so if you could git pull the branch and test it again! I don't really get why it doesn't find the class, I never had this problem on my compter or on Joplin. If you have any clue, feel free to give me your insights :blush:

**Comment by alexfoias** [comment]
```
[26/02/21 3:35:59] (base) alex@NeuroPoly-MacBook-Pro cli % python manual_correction.py -path-in /Volumes/temp/sebeda/segmentation_350/ukbiobank_seg/data_processed/ -config /Volumes/temp/sebeda/segmentation_350/manual_seg_test.yml 
Enter your name (Firstname Lastname). It will be used to generate a json sidecar with each corrected file: Alex Foias
In ITK-SNAP, correct the segmentation, then save it with the same name (overwrite).
ITK-SNAP not found. Please install it before using this program or check if it was added to PATH variable. Exit program.
```

**Comment by alexfoias** [comment]
After adding to path:

```
[26/02/21 3:36:34] (base) alex@NeuroPoly-MacBook-Pro cli % export PATH=/Applications/ITK-SNAP.app/Contents/bin:$PATH 
[26/02/21 3:47:08] (base) alex@NeuroPoly-MacBook-Pro cli % python manual_correction.py -path-in /Volumes/temp/sebeda/segmentation_350/ukbiobank_seg/data_processed/ -config /Volumes/temp/sebeda/segmentation_350/manual_seg_test.yml
Enter your name (Firstname Lastname). It will be used to generate a json sidecar with each corrected file: AF
WARNING! The file ./derivatives/labels/sub-1000394/anat/sub-1000394_T2w_seg-manual.nii.gz already exists. Would you like to overwrite it? [y/n] n
In ITK-SNAP, correct the segmentation, then save it with the same name (overwrite).
[26/02/21 3:47:25] (base) alex@NeuroPoly-MacBook-Pro cli % libpng warning: sCAL: invalid unit
libpng warning: sCAL: invalid unit
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: sCAL: invalid unit

```

**Review by alexfoias — APPROVED** [review]

**Pull request merged**
