### PR TITLE
Add subjects to exclude

### PR DESCRIPTION
**Pull request by sandrinebedard**
## Description
This PR adds subjects to exclude in `exclude.yml`. The main causes for exclusion are that the FOV doesn't cover C2-C3 and poor data quality.
I observed the following artefact multiple times:
(sub-1132718_T1w.nii.gz)
image
image

I am not sure what could be the cause here.

### CODE REVIEW

**Comment by jcohenadad** [comment]
hum... could be aliasing of fat signal and/or motion. But i'm not sure i would necessarily remove it, as long as the output segmentation is correct: we do "see" the spinal cord between c2-c3, no?

**Comment by sandrinebedard** [comment]
> But i'm not sure i would necessarily remove it, as long as the output segmentation is correct: we do "see" the spinal cord between c2-c3, no?

Yes, I agree for that image, but it maybe was not the best example 😬, my bad, I agree we can keep it. Some others also have motion artefact in addition.
I'll check again with the segmentations for these images! 

I find it ambiguous to know if we have enough slices to compute cord CSA:
e.g:
image

**Comment by jcohenadad** [comment]
in the case showed in https://github.com/sct-pipeline/ukbiobank-spinalcord-csa/pull/60#issuecomment-818246380, i would say there are not enough slices

**Comment by sandrinebedard** [comment]
@jcohenadad I removed the images from the list according your remark in https://github.com/sct-pipeline/ukbiobank-spinalcord-csa/pull/60#issuecomment-818228788 and kept the images that we would not have enough slices with the segmentation for cord CSA, everything should be ok now

**Review by jcohenadad — APPROVED** [review]

**Pull request merged**
